<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType><TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>EOG</AssemblyName><RootNamespace>EternalVoidPanel</RootNamespace>
    <ApplicationIcon>Assets\eog-geass.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\eog-geass.png" />
    <Resource Include="Assets\eog-geass.ico" />
  </ItemGroup>
</Project>
